spring.datasource.url=jdbc:postgresql://pg-4e1437f-codzgarage-38ef.h.aivencloud.com:17660/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_AQBBQ33QU__znO4zIge
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect